"use client";
import {useEffect,useState} from "react";

type Cat={id:string;slug:string;name_hi:string;name_en:string};
type Scripture={id:string;slug:string;title_hi:string;title_en:string;status:string;price_inr:number;rights_status?:string;category_hi?:string;chapter_count?:number;verse_count?:number;current_file_count?:number};
type Chapter={id:string;chapter_number:number;title_hi:string|null;title_en:string|null;verse_count:number};
type Verse={id:string;verse_number:number;text_hi:string|null;text_en:string|null;source_reference:string|null};
type FileItem={id:string;original_name:string;mime_type:string;size_bytes:number;checksum_sha256:string|null;is_private:boolean;version_number:number;is_current:boolean;created_at:string};
const emptyForm={category_id:"",slug:"",title_hi:"",title_en:"",price_inr:"9",status:"DRAFT",rights_status:"",description_hi:"",description_en:"",author_tradition:"",edition:"",language:"hi"};
const blankChapter={chapter_number:"1",title_hi:"",title_en:""};
const blankVerse={verse_number:"1",text_hi:"",text_en:"",source_reference:""};
export default function CMSPage(){
 const [cats,setCats]=useState<Cat[]>([]),[items,setItems]=useState<Scripture[]>([]),[selected,setSelected]=useState<Scripture|null>(null),[chapters,setChapters]=useState<Chapter[]>([]),[chapterId,setChapterId]=useState(""),[verses,setVerses]=useState<Verse[]>([]),[files,setFiles]=useState<FileItem[]>([]),[form,setForm]=useState<any>(emptyForm),[chapterForm,setChapterForm]=useState(blankChapter),[verseForm,setVerseForm]=useState(blankVerse),[editingChapter,setEditingChapter]=useState<string|null>(null),[editingVerse,setEditingVerse]=useState<string|null>(null),[replaceId,setReplaceId]=useState<string|null>(null),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);
 async function load(){const [c,s]=await Promise.all([fetch('/api/admin/categories'),fetch('/api/admin/scriptures')]);setCats((await c.json()).items||[]);setItems((await s.json()).items||[])}
 useEffect(()=>{load()},[]);
 async function refreshChapters(id:string){const r=await fetch(`/api/admin/chapters?scriptureId=${id}`);setChapters((await r.json()).items||[])}
 async function refreshFiles(id:string){const r=await fetch(`/api/admin/files?scriptureId=${id}`);setFiles((await r.json()).items||[])}
 async function select(s:Scripture){setSelected(s);setForm({...emptyForm,...s,category_id:(cats.find(c=>c.name_hi===s.category_hi)?.id)||""});setChapterId("");setVerses([]);setEditingChapter(null);setEditingVerse(null);await Promise.all([refreshChapters(s.id),refreshFiles(s.id)])}
 async function selectChapter(id:string){setChapterId(id);setEditingVerse(null);if(!id){setVerses([]);return}const r=await fetch(`/api/admin/verses?chapterId=${id}`);setVerses((await r.json()).items||[])}
 async function saveScripture(e:React.FormEvent){e.preventDefault();setBusy(true);setMsg("");const payload={...form,price_inr:Number(form.price_inr)};const r=await fetch(selected?`/api/admin/scriptures/${selected.id}`:'/api/admin/scriptures',{method:selected?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const j=await r.json();setBusy(false);if(!r.ok){setMsg(j.error||'Save failed');return}setMsg(selected?'Granth updated':'Granth created');await load();if(j.item)await select(j.item)}
 function startChapter(c:Chapter){setEditingChapter(c.id);setChapterForm({chapter_number:String(c.chapter_number),title_hi:c.title_hi||'',title_en:c.title_en||''})}
 async function saveChapter(e:React.FormEvent){e.preventDefault();if(!selected)return;const payload={...chapterForm,chapter_number:Number(chapterForm.chapter_number)};const url=editingChapter?`/api/admin/chapters/${editingChapter}`:'/api/admin/chapters';const r=await fetch(url,{method:editingChapter?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...payload,...(editingChapter?{}:{scripture_id:selected.id})})});const j=await r.json();setMsg(r.ok?(editingChapter?'Chapter updated':'Chapter added'):(j.error||'Chapter save failed'));if(r.ok){setEditingChapter(null);setChapterForm({chapter_number:String(chapters.length+1),title_hi:'',title_en:''});await refreshChapters(selected.id)}}
 async function deleteChapter(id:string){if(!selected||!confirm('Chapter aur uske verses delete karne hain?'))return;const r=await fetch(`/api/admin/chapters/${id}`,{method:'DELETE'});const j=await r.json();setMsg(r.ok?'Chapter deleted':j.error||'Delete failed');if(r.ok){if(chapterId===id){setChapterId('');setVerses([])}await refreshChapters(selected.id)}}
 function startVerse(v:Verse){setEditingVerse(v.id);setVerseForm({verse_number:String(v.verse_number),text_hi:v.text_hi||'',text_en:v.text_en||'',source_reference:v.source_reference||''})}
 async function saveVerse(e:React.FormEvent){e.preventDefault();if(!chapterId)return;const payload={...verseForm};const url=editingVerse?`/api/admin/verses/${editingVerse}`:'/api/admin/verses';const r=await fetch(url,{method:editingVerse?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...payload,verse_number:Number(verseForm.verse_number),...(editingVerse?{}:{chapter_id:chapterId})})});const j=await r.json();setMsg(r.ok?(editingVerse?'Verse updated':'Verse added'):(j.error||'Verse save failed'));if(r.ok){setEditingVerse(null);setVerseForm({verse_number:String(verses.length+1),text_hi:'',text_en:'',source_reference:''});await selectChapter(chapterId)}}
 async function deleteVerse(id:string){if(!confirm('Ye verse delete karna hai?'))return;const r=await fetch(`/api/admin/verses/${id}`,{method:'DELETE'});const j=await r.json();setMsg(r.ok?'Verse deleted':j.error||'Delete failed');if(r.ok)await selectChapter(chapterId)}
 async function upload(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file||!selected)return;setBusy(true);const fd=new FormData();fd.append('scripture_id',selected.id);fd.append('file',file);if(replaceId)fd.append('replace_file_id',replaceId);const r=await fetch('/api/storage/upload',{method:'POST',body:fd});const j=await r.json();setMsg(r.ok?(replaceId?`File replaced — version ${j.version}`:'Verified private file uploaded'):j.error||'Upload failed');setBusy(false);e.target.value='';setReplaceId(null);if(r.ok)await refreshFiles(selected.id)}
 async function deleteFile(id:string){if(!confirm('Is file version ko delete karna hai?'))return;const r=await fetch(`/api/admin/files?id=${id}`,{method:'DELETE'});const j=await r.json();setMsg(r.ok?'File version deleted':j.error||'Delete failed');if(r.ok&&selected)await refreshFiles(selected.id)}
 return <div><div className="adminHeader"><div><p className="eyebrow">Content Management</p><h1>Granth CMS</h1><p className="muted">Category → Scripture → Chapter → Verse → Verified private file → Publish.</p></div></div>
 <div className="cms-columns"><section className="panel"><h2>{selected?'Edit Granth':'New Granth'}</h2><form onSubmit={saveScripture} className="stack-form"><label>Hindi title<input required value={form.title_hi} onChange={e=>setForm({...form,title_hi:e.target.value})}/></label><label>English title<input required value={form.title_en} onChange={e=>setForm({...form,title_en:e.target.value})}/></label><label>Slug<input required value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})}/></label><label>Category<select required value={form.category_id} onChange={e=>setForm({...form,category_id:e.target.value})}><option value="">Select</option>{cats.map(c=><option key={c.id} value={c.id}>{c.name_hi} · {c.name_en}</option>)}</select></label><label>Price (₹)<input type="number" min="0" value={form.price_inr} onChange={e=>setForm({...form,price_inr:e.target.value})}/></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>DRAFT</option><option>PUBLISHED</option><option>ARCHIVED</option></select></label><label>Rights / source note<textarea required value={form.rights_status||''} onChange={e=>setForm({...form,rights_status:e.target.value})}/></label><label>Hindi description<textarea value={form.description_hi||''} onChange={e=>setForm({...form,description_hi:e.target.value})}/></label><label>English description<textarea value={form.description_en||''} onChange={e=>setForm({...form,description_en:e.target.value})}/></label><label>Author / tradition<input value={form.author_tradition||''} onChange={e=>setForm({...form,author_tradition:e.target.value})}/></label><label>Edition<input value={form.edition||''} onChange={e=>setForm({...form,edition:e.target.value})}/></label><button className="primary" disabled={busy}>{busy?'Saving…':selected?'Save Granth':'Create Granth'}</button></form>{msg&&<p className="form-msg">{msg}</p>}</section>
 <section className="panel"><div className="cms-section-head"><h2>Catalog</h2><button onClick={()=>{setSelected(null);setForm(emptyForm);setMsg('')}}>＋ New</button></div>{items.length===0?<div className="empty">No scriptures yet.</div>:<div className="cms-list">{items.map(s=><button className={selected?.id===s.id?'cms-row selected':'cms-row'} key={s.id} onClick={()=>select(s)}><span><strong>{s.title_hi}</strong><small>{s.title_en} · /{s.slug}</small></span><span>{s.category_hi||'—'}</span><span className="badge">{s.status}</span><span>₹{s.price_inr}</span></button>)}</div>}
 {selected&&<><hr/><div className="publish-check"><div><b>Publishing checklist</b><small>All four checks must pass before the API allows PUBLISHED.</small></div><div className={selected.rights_status?'check-ok':'check-no'}>✓ Rights/source note</div><div className={(selected.chapter_count||0)>0?'check-ok':'check-no'}>✓ Chapters: {selected.chapter_count||0}</div><div className={(selected.verse_count||0)>0?'check-ok':'check-no'}>✓ Verses: {selected.verse_count||0}</div><div className={(selected.current_file_count||0)>0?'check-ok':'check-no'}>✓ Current private file: {(selected.current_file_count||0)>0?'Ready':'Missing'}</div></div><div className="cms-section-head"><h2>Chapters</h2><button onClick={()=>{setEditingChapter(null);setChapterForm({chapter_number:String(chapters.length+1),title_hi:'',title_en:''})}}>＋ New Chapter</button></div><form className="inline-form" onSubmit={saveChapter}><input type="number" min="1" value={chapterForm.chapter_number} onChange={e=>setChapterForm({...chapterForm,chapter_number:e.target.value})}/><input placeholder="Hindi title" value={chapterForm.title_hi} onChange={e=>setChapterForm({...chapterForm,title_hi:e.target.value})}/><input placeholder="English title" value={chapterForm.title_en} onChange={e=>setChapterForm({...chapterForm,title_en:e.target.value})}/><button>{editingChapter?'Update':'Add'}</button>{editingChapter&&<button type="button" onClick={()=>setEditingChapter(null)}>Cancel</button>}</form><div className="chapter-list">{chapters.map(c=><div key={c.id} className={chapterId===c.id?'chapter-item active':'chapter-item'}><button className="chapter-main" onClick={()=>selectChapter(c.id)}><span>अध्याय {c.chapter_number} · {c.title_hi||c.title_en||'Untitled'}</span><small>{c.verse_count} verses</small></button><span className="mini-actions"><button onClick={()=>startChapter(c)}>Edit</button><button onClick={()=>deleteChapter(c.id)}>Delete</button></span></div>)}</div>
 {chapterId&&<><div className="cms-section-head"><h2>Verses</h2><button onClick={()=>{setEditingVerse(null);setVerseForm({...blankVerse,verse_number:String(verses.length+1)})}}>＋ New Verse</button></div><form className="verse-form" onSubmit={saveVerse}><input type="number" min="1" value={verseForm.verse_number} onChange={e=>setVerseForm({...verseForm,verse_number:e.target.value})}/><textarea placeholder="Hindi verified text" value={verseForm.text_hi} onChange={e=>setVerseForm({...verseForm,text_hi:e.target.value})}/><textarea placeholder="English verified text" value={verseForm.text_en} onChange={e=>setVerseForm({...verseForm,text_en:e.target.value})}/><input placeholder="Source reference" value={verseForm.source_reference} onChange={e=>setVerseForm({...verseForm,source_reference:e.target.value})}/><button>{editingVerse?'Update Verse':'Add Verse'}</button>{editingVerse&&<button type="button" onClick={()=>setEditingVerse(null)}>Cancel</button>}</form><div className="verse-list">{verses.map(v=><div className="verse-admin" key={v.id}><b>#{v.verse_number}</b><div><div>{v.text_hi||'—'}</div><small>{v.source_reference||'No source reference'}</small></div><span className="mini-actions"><button onClick={()=>startVerse(v)}>Edit</button><button onClick={()=>deleteVerse(v.id)}>Delete</button></span></div>)}</div></>}
 <hr/><div className="cms-section-head"><h2>Verified Content Files</h2>{files.some(f=>f.is_current)&&<span className="badge">Current version protected</span>}</div><p className="muted">Private S3/R2 storage. PDF/EPUB, max 100 MB. Replacement creates a new version and keeps history.</p><label className="upload-box">＋ {replaceId?'Replace selected file':'Upload PDF / EPUB'}<input type="file" accept="application/pdf,application/epub+zip" onChange={upload}/></label>{replaceId&&<p className="form-msg">Replacement selected. Choose the new PDF/EPUB now. <button type="button" onClick={()=>setReplaceId(null)}>Cancel</button></p>}{files.map(f=><div className={f.is_current?'file-row current-file':'file-row'} key={f.id}><span><b>v{f.version_number} · {f.original_name}</b><small>{f.mime_type} · {(f.size_bytes/1024/1024).toFixed(2)} MB · SHA-256 {f.checksum_sha256?.slice(0,16)}…</small></span><span className="badge">{f.is_current?'CURRENT':'HISTORY'}</span><span className="mini-actions">{f.is_current&&<button onClick={()=>setReplaceId(f.id)}>Replace</button>}<button onClick={()=>deleteFile(f.id)}>Delete</button></span></div>)}</>}
 </section></div></div>
}


