'use client';
import {useEffect,useState} from 'react';
export default function EntitlementsAdmin(){
 const [items,setItems]=useState<any[]>([]),[users,setUsers]=useState<any[]>([]),[scriptures,setScriptures]=useState<any[]>([]),[q,setQ]=useState(''),[msg,setMsg]=useState(''),[grant,setGrant]=useState({user_id:'',scripture_id:''});
 const load=()=>fetch('/api/admin/entitlements?q='+encodeURIComponent(q)).then(r=>r.json()).then(j=>setItems(j.items||[]));
 useEffect(()=>{load();Promise.all([fetch('/api/admin/users').then(r=>r.json()),fetch('/api/admin/scriptures').then(r=>r.json())]).then(([u,s])=>{setUsers(u.items||[]);setScriptures(s.items||[])})},[]);
 async function change(id:string,status:string){setMsg('Saving…');const r=await fetch('/api/admin/entitlements',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,status})});const j=await r.json();setMsg(r.ok?'Saved.':j.error||'Failed');if(r.ok)load()}
 async function manualGrant(e:React.FormEvent){e.preventDefault();setMsg('Granting…');const r=await fetch('/api/admin/entitlements',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(grant)});const j=await r.json();setMsg(r.ok?'Access granted.':j.error||'Grant failed');if(r.ok){setGrant({user_id:'',scripture_id:''});load()}}
 return <section><div className="adminHeader"><div><p className="eyebrow">Access</p><h1>Entitlements</h1><p className="muted">Purchased access, manual grants and revocations. Manual grants are audited.</p></div><span className="form-msg">{msg}</span></div>
 <div className="adminGrid"><form className="panel" onSubmit={manualGrant}><h2>Manual access grant</h2><label>User<select required value={grant.user_id} onChange={e=>setGrant({...grant,user_id:e.target.value})}><option value="">Select user</option>{users.filter(u=>u.role==='USER').map(u=><option key={u.id} value={u.id}>{u.name||u.email} · {u.email||'no email'}</option>)}</select></label><label>Granth<select required value={grant.scripture_id} onChange={e=>setGrant({...grant,scripture_id:e.target.value})}><option value="">Select Granth</option>{scriptures.map(s=><option key={s.id} value={s.id}>{s.title_en} · {s.status}</option>)}</select></label><button className="primary">Grant Active Access</button></form>
 <div className="panel"><h2>Search</h2><input value={q} placeholder="Name, email, Granth or slug" onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')load()}}/><div className="action-row"><button className="primary" onClick={load}>Search</button><button onClick={()=>{setQ('');setTimeout(load,0)}}>Clear</button></div></div></div>
 <div className="panel"><div className="table"><div className="tr head"><span>User / Granth</span><span>Order</span><span>Status</span><span>Action</span></div>{items.map(x=><div className="tr" key={x.id}><span><strong>{x.name||'—'}</strong><small>{x.email||'—'} · {x.title_en}</small></span><span>{x.razorpay_order_id||'Manual'}</span><span>{x.status}<small>{new Date(x.granted_at).toLocaleString()}</small></span><span>{x.status==='ACTIVE'?<button onClick={()=>change(x.id,'REVOKED')}>Revoke</button>:<button className="primary" onClick={()=>change(x.id,'ACTIVE')}>Activate</button>}</span></div>)}</div></div></section>
}
