'use client';
import {useEffect,useState} from 'react';
export default function TelegramAdmin(){
 const [d,setD]=useState<any>(null),[text,setText]=useState('Sanatan Gyan Telegram admin test message'),[key,setKey]=useState('announcement_enabled'),[value,setValue]=useState('false'),[msg,setMsg]=useState('');
 const load=()=>fetch('/api/admin/telegram').then(r=>r.json()).then(setD);useEffect(load,[]);
 async function post(body:any){const r=await fetch('/api/admin/telegram',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();setMsg(r.ok?'Saved.':j.error||'Action failed');if(r.ok)load()}
 async function test(){setMsg('Sending…');const r=await fetch('/api/admin/telegram',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'test_message',text})});const j=await r.json();setMsg(r.ok?'Test message processed for configured admin IDs.':j.error||'Failed')}
 return <section><div className="adminHeader"><div><p className="eyebrow">Telegram Control</p><h1>Telegram Admin</h1><p className="muted">Bot operations stay webhook-based; AANU remains isolated on its separate server.</p></div><span className="status">{d?.configured?'Bot configured':'Bot token missing'}</span></div>
 <div className="adminGrid"><div className="panel"><h2>Bot & webhook status</h2>{d?<><p><b>{d.bot?.result?.first_name||'Telegram Bot'}</b> {d.bot?.result?.username?`@${d.bot.result.username}`:''}</p><p className="muted">Token: {d.configured?'configured':'missing'} · Webhook secret: {d.webhookConfigured?'configured':'missing'}</p><p className="muted">Configured admin IDs: {(d.adminIds||[]).join(', ')}</p></>:<p>Loading…</p>}</div>
 <div className="panel"><h2>Admin test message</h2><p className="muted">Targets only the configured Telegram admin IDs.</p><textarea value={text} onChange={e=>setText(e.target.value)} rows={4} style={{width:'100%',padding:12,border:'1px solid var(--line)',borderRadius:10,font:'inherit'}}/><div className="action-row"><button className="primary" disabled={!d?.configured} onClick={test}>Send test</button><span className="form-msg">{msg}</span></div></div>
 <div className="panel"><h2>Telegram settings</h2><p className="muted">Settings are stored as JSONB; secrets never belong here.</p><label>Setting key<input value={key} onChange={e=>setKey(e.target.value)}/></label><label>JSON value<input value={value} onChange={e=>setValue(e.target.value)} placeholder={'false / true / \"text\" / 123'}/></label><button className="primary" onClick={()=>{try{post({action:'set_setting',key,value:JSON.parse(value)})}catch{setMsg('Value must be valid JSON.')}}}>Save setting</button><div className="setting-list">{(d?.settings||[]).map((s:any)=><div className="file-row" key={s.key}><span><b>{s.key}</b><small>{JSON.stringify(s.value)} · updated {new Date(s.updated_at).toLocaleString()}</small></span></div>)}</div></div>
 <div className="panel"><h2>Operational boundaries</h2><ul className="checklist"><li>Webhook-based processing only; no competing polling process.</li><li>AANU integration remains an external contract.</li><li>Admin test messages use explicit configured recipients.</li><li>Bot token and webhook secret remain environment-only.</li></ul></div></div></section>
}
